// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';


function f(param, param$1) {
  return true;
}

var check = true;

exports.f = f;
exports.check = check;
/* No side effect */
